# Generated by Django 3.0.5 on 2021-01-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
