# Generated by Django 3.0.5 on 2021-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0002_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/project1.jpg', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product_image/dm.jpg', null=True, upload_to='product_image/'),
        ),
    ]
